server:
  port: 8082

spring:
  application:
    name: investment-service
  config:
    import: "optional:configserver:http://config-server:8888"
  datasource:
    url: jdbc:postgresql://investment-db:5432/investment_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true